# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a3980e4e8e0768825697140c0d9c81ff"
name = "ugc-app-v1"
application_url = "https://suggestions-rebate-strategic-median.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,write_files,write_products"

[auth]
redirect_urls = [ "https://suggestions-rebate-strategic-median.trycloudflare.com/api/auth" ]

[app_proxy]
url = "https://suggestions-rebate-strategic-median.trycloudflare.com/api/videos"
subpath = "ugc-videos"
prefix = "apps"
